name: Remove Ads

on:
  push:
    branches:
      - main

jobs:
  update-Ad-Free:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Remove Ads
        run: |
          git fetch origin
          if git branch --list | grep -q 'Ad-Free'; then
            git checkout Ad-Free
            git pull origin Ad-Free
            git merge main --no-edit
          else
            git checkout -b Ad-Free
          fi

      - name: Remove first 9 lines from main.js
        run: |
          sed -i '1,9d' static/assets/js/main.js
  
      - name: Commit changes
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        run: |
          git config --global user.name "${GIT_USERNAME}"
          git config --global user.email "${GIT_EMAIL}"
          git add static/assets/js/main.js
          git commit -m "Remove specific JS code from main.js"

      - name: Push changes to Ad-Free branch
        run: |
          git push origin Ad-Free --force
